### ISSUE TITLE
How much VRAM and RAM are needed to run, why do I kill the program when running it

### ISSUE THREAD

**Issue by libai-lab** [franciszzj/Leffa#1]
How much VRAM and RAM are needed to run, why do I kill the program when running it
d will be ignored. Please verify your config.json configuration file.
The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 37000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Killed

**Comment by franciszzj** [comment]
The current demo requires 40GB of GPU memory to run because it loads both the virtual try-on and pose transfer models simultaneously.
If you don’t have a GPU with 40GB of memory, you can consider loading just one of the models. In this case, a GPU with 24GB of memory should be sufficient.

**Comment by vforvasquez** [comment]
How do I just load one model at a time?

**Comment by Geruldas** [comment]
I made it like this, i focused on try on

`import numpy as np
from PIL import Image
from huggingface_hub import snapshot_download
from leffa.transform import LeffaTransform
from leffa.model import LeffaModel
from leffa.inference import LeffaInference
from utils.garment_agnostic_mask_predictor import AutoMasker
from utils.densepose_predictor import DensePosePredictor
from utils.utils import resize_and_center

import gradio as gr

# Download checkpoints
snapshot_download(repo_id="franciszzj/Leffa", local_dir="./ckpts")

# Initialize Mask Predictor
mask_predictor = AutoMasker(
    densepose_path="./ckpts/densepose",
    schp_path="./ckpts/schp",
)

# Initialize DensePose Predictor
densepose_predictor = DensePosePredictor(
    config_path="./ckpts/densepose/densepose_rcnn_R_50_FPN_s1x.yaml",
    weights_path="./ckpts/densepose/model_final_162be9.pkl",
)

# Initialize Virtual Try-On Model and Inference
vt_model = LeffaModel(
    pretrained_model_name_or_path="./ckpts/stable-diffusion-inpainting",
    pretrained_model="./ckpts/virtual_tryon.pth",
)
vt_inference = LeffaInference(model=vt_model)


def leffa_predict(src_image_path, ref_image_path):
    """
    Predict function for Virtual Try-On.
    """
    src_image = Image.open(src_image_path)
    ref_image = Image.open(ref_image_path)
    src_image = resize_and_center(src_image, 768, 1024)
    ref_image = resize_and_center(ref_image, 768, 1024)

    src_image_array = np.array(src_image)
    ref_image_array = np.array(ref_image)

    # Generate Mask for Virtual Try-On
    src_image = src_image.convert("RGB")
    mask = mask_predictor(src_image, "upper")["mask"]

    # Generate DensePose Segmentation
    src_image_seg_array = densepose_predictor.predict_seg(src_image_array)
    densepose = Image.fromarray(src_image_seg_array)

    # Prepare Data for Inference
    transform = LeffaTransform()

    data = {
        "src_image": [src_image],
        "ref_image": [ref_image],
        "mask": [mask],
        "densepose": [densepose],
    }
    data = transform(data)

    # Perform Inference
    output = vt_inference(data)
    gen_image = output["generated_image"][0]
    return np.array(gen_image)


if __name__ == "__main__":
    title = "## Leffa: Learning Flow Fields in Attention for Controllable Person Image Generation"
    link = "[📚 Paper](https://arxiv.org/abs/2412.08486) - [🔥 Demo](https://huggingface.co/spaces/franciszzj/Leffa) - [🤗 Model](https://huggingface.co/franciszzj/Leffa)"
    description = "Leffa is a unified framework for controllable person image generation that enables precise manipulation of both appearance (i.e., virtual try-on)."

    with gr.Blocks(theme=gr.themes.Default(primary_hue=gr.themes.colors.pink, secondary_hue=gr.themes.colors.red)).queue() as demo:
        gr.Markdown(title)
        gr.Markdown(link)
        gr.Markdown(description)

        with gr.Tab("Control Appearance (Virtual Try-on)"):
            with gr.Row():
                with gr.Column():
                    gr.Markdown("#### Person Image")
                    vt_src_image = gr.Image(
                        sources=["upload"],
                        type="filepath",
                        label="Person Image",
                        width=512,
                        height=512,
                    )

                    gr.Examples(
                        inputs=vt_src_image,
                        examples_per_page=5,
                        examples=[
                            "./ckpts/examples/person1/01350_00.jpg",
                            "./ckpts/examples/person1/01376_00.jpg",
                            "./ckpts/examples/person1/01416_00.jpg",
                            "./ckpts/examples/person1/05976_00.jpg",
                            "./ckpts/examples/person1/06094_00.jpg",
                        ],
                    )

                with gr.Column():
                    gr.Markdown("#### Garment Image")
                    vt_ref_image = gr.Image(
                        sources=["upload"],
                        type="filepath",
                        label="Garment Image",
                        width=512,
                        height=512,
                    )

                    gr.Examples(
                        inputs=vt_ref_image,
                        examples_per_page=5,
                        examples=[
                            "./ckpts/examples/garment/01449_00.jpg",
                            "./ckpts/examples/garment/01486_00.jpg",
                            "./ckpts/examples/garment/01853_00.jpg",
                            "./ckpts/examples/garment/02070_00.jpg",
                            "./ckpts/examples/garment/03553_00.jpg",
                        ],
                    )

                with gr.Column():
                    gr.Markdown("#### Generated Image")
                    vt_gen_image = gr.Image(
                        label="Generated Image",
                        width=512,
                        height=512,
                    )

                    with gr.Row():
                        vt_gen_button = gr.Button("Generate")

                # Connect the Generate button to the prediction function
                vt_gen_button.click(
                    fn=leffa_predict,
                    inputs=[vt_src_image, vt_ref_image],
                    outputs=[vt_gen_image],
                )

    demo.launch(share=True, server_port=7860)
`

**Comment by NielHung** [comment]
我电脑有24G显存，注释掉：self.pt_inference = LeffaInference(model=pt_model) 后
还是直接就死机了

**Comment by NielHung** [comment]
更简单的，注释掉：
        pt_model = LeffaModel(
            # pretrained_model_name_or_path="./ckpts/stable-diffusion-xl-1.0-inpainting-0.1",
            pretrained_model_name_or_path=os.path.join(leffa_model_dir, "stable-diffusion-xl-1.0-inpainting-0.1"),
            # pretrained_model="./ckpts/pose_transfer.pth",
            pretrained_model=os.path.join(leffa_model_dir, "pose_transfer.pth"),
        )
        self.pt_inference = LeffaInference(model=pt_model)
        
显存用了大概8.5G
