### ISSUE TITLE
pose control change the appearance

### ISSUE THREAD

**Issue by Dan1900** [franciszzj/Leffa#10]
![企业微信截图_17344188231868](https://github.com/user-attachments/assets/31effb56-7833-4d25-b1d2-f15f2d122cfc)

**Comment by franciszzj** [comment]
Thank you for your example.  
Since the currently released open-source models are trained only on academic datasets, there is a certain bias, and they cannot yet handle all out-of-distribution cases effectively. We will continue to improve this.

**Comment by Dan1900** [comment]
Thank you for your reply.
