### ISSUE TITLE
Other parts for tryon

### ISSUE THREAD

**Issue by mao-code** [franciszzj/Leffa#13]
I have utilize the parts that this method provides like upper, lower, inner, outer, overall. Can it tryon accessories or shoes?

Thank you for your help!

**Comment by Blackteaxx** [comment]
> I have utilize the parts that this method provides like upper, lower, inner, outer, overall. Can it tryon accessories or shoes?
> 
> Thank you for your help!

Can I get some details about tryon about _lower, inner, outer, overall._? I am not clear about the deeper settings in the code. thx!!

**Comment by franciszzj** [comment]
Currently, this model does not support accessories or shoes because we did not train it on the corresponding datasets.

**Comment by mao-code** [comment]
OK. Thank you!
