### ISSUE TITLE
Weights for model without Leffa Loss

### ISSUE THREAD

**Issue by pvnieo** [franciszzj/Leffa#5]
Hi,

Thank you for sharing the code and the weights. I saw that you released the weights for the model trained on VITON-HD and DressCode. Is it possible to share the weights for the models trained without the leffa loss, used for the ablation study?

Thank in advance for your help.

Best

**Comment by franciszzj** [comment]
Thank you for your interest.  
Currently, we do not plan to release the intermediate models, but we will assess the situation and decide in the future.  
However, if you wish to conduct ablation studies quickly, you can try replicating our model structure and following the training methods provided in the paper. This process should not be very difficult.
