### ISSUE TITLE
袖子有问题

### ISSUE THREAD

**Issue by StartHua** [franciszzj/Leffa#9]
![00012_00](https://github.com/user-attachments/assets/8322756a-e855-4a26-8b5d-910a928a5416)
![02305_00](https://github.com/user-attachments/assets/51b0e801-cddb-4290-9204-317cc8ad05e2)
![gen_image_5_22](https://github.com/user-attachments/assets/04b28654-ceb6-4080-979f-6cb55a6cfa85)

**Comment by franciszzj** [comment]
Thank you.  
This is a valuable bad case, and we will work on further improvements.
